### ISSUE TITLE
Unclear configuration instructions

### ISSUE THREAD

**Issue by jbrepogmailcom** [dlashua/torque2mqtt#3]
What are following settings?
```
server:
  ip: 0.0.0.0
  port: 5000
```
I have set in torque settings the web server `<my IP address>:5000`, but it does not connect. Tried without :5000, nothing.

**Comment by geotibi** [comment]
Hello,

I'm also interested on this configuration. I did the same but it's not working. The container is running ok in docker. Is it any path that need to be added after the port like http://IP ADDRESS:5000/api  or    http://IP ADDRESS:5000 is enough?

**Comment by krisstakos** [comment]
So, I've read trough the code and the config is a follows:

```
server:
  ip: 0.0.0.0 -> the address of the host, hence where the server is working
  port: 5000 -> the port of that server
 mqtt: -> obviously for the mqtt serer
  host: 192.168.0.100 -> where is the mqtt server
  port: 1883
  username: username
  password: password
  prefix: torque

```

In the torque app you should put ip and port of the server.
You know if it's port-forwarded you should put your public ip and port
